### ISSUE TITLE
assertation error

### ISSUE THREAD

**Issue by Arcanum7** [mfg92/hantek1008py#1]
`sam@sam-desktop:/d/git/hantek1008py$ python3.6 csvexport.py 1.csv -s 1
INFO   : Connecting...
INFO   : Connection established
INFO   : Initialising...
Traceback (most recent call last):
  File "csvexport.py", line 501, in <module>
    do_sampling_rate_measure=args.do_sampling_rate_measure)
  File "csvexport.py", line 110, in main
    zero_offset_shift_compensation_function, zero_offset_shift_compensation_function_time_offset_sec)
  File "csvexport.py", line 178, in connect
    device.init()
  File "/d/git/hantek1008py/hantek1008.py", line 211, in init
    self._init1()
  File "/d/git/hantek1008py/hantek1008.py", line 231, in _init1
    assert response == bytes.fromhex("00080008000800080008000800080008d407c907ef07cd07df07eb07c707d707"
AssertionError
`

when i try to start script, i have this error.
my hantek is 1008c. may it be problem?

**Comment by Arcanum7** [comment]
i understand what it was
i changed this code to mine responses:
        response = self.__send_cmd(0xb5, response_length=64, echo_expected=False,
                                   sec_till_response_request=0.0193)  # 181
        assert response == bytes.fromhex("00080008000800080008000800080008990791079707a4079607aa0797078607"
                                        "a9079e07a607aa07a107b407a8079507c307b407bd07b507b307c307c207ac07")
        
        response = self.__send_cmd(0xb6, response_length=64, echo_expected=False)  # 182
        assert response == bytes.fromhex("04040404040404040404040404040404c000c300c300c300c000c100c100c000"
                                        "96009600960096009600950096009400f801f701f601f801f801f501f901f701")

        response = self.__send_cmd(0xe5, response_length=2, echo_expected=False)
        assert response == bytes.fromhex("a8 06")

        response = self.__send_cmd(0xf7, response_length=64, echo_expected=False)
        assert response == bytes.fromhex("31fd9afb68fa55f86f007000700071006f006f0070006e00a701ad01ab01ac01"
                                        "a601a801a801a401dc02e602e402e402dd02df02df02da029cff9aff9bff9aff")
        response = self.__send_cmd(0xf8, response_length=64, echo_expected=False)
        assert response == bytes.fromhex("9cff9cff9eff9dffd8fed3fed5fed2fed7fed5fedbfedbfe5efe56fe58fe54fe"
                                        "5dfe5afe62fe62fe74ff74ff75ff74ff75ff74ff76ff76ff85fe86fe88fe84fe")

        response = self.__send_cmd(0xfa, response_length=56, echo_expected=False)
        assert response == bytes.fromhex("89fe87fe8bfe8cfe8a018a0189018a0188018801890186018c028c028a028b02"
                                        "870288028b02860299fd9bfd9ffd98fda1fd9dfda7fda6fd")

**Comment by mfg92** [comment]
Oh thats interessting. I have no idea what these comamnds and responses are good for. But they were always the same for the Hantek1008C I use. Now you get different results for the same commands. So i think i should not have any asserts after these commands.

**Comment by mfg92** [comment]
are the reported ones the only asserts that were triggered?
