### ISSUE TITLE
Hantek 1008c/b

### ISSUE THREAD

**Issue by UpDownSide** [mfg92/hantek1008py#4]
Do i have to install any other software? Or just this one makes it? Is it possible to add it to other software with this script? Will it work with a rpi?

**Comment by mfg92** [comment]
You need to have python installed together with the python packages _pyusb_ and _overrides_.
See https://github.com/mfg92/hantek1008py#notes

You can integrate [hantek1008.py](https://github.com/mfg92/hantek1008py/blob/master/hantek1008.py) into your own python project or call _csvexport.py_ and import the data from that file into your project.

I should work on an Raspberry Pi.

**Comment by UpDownSide** [comment]
Hi! Does it work with openhantek or other software?

A sábado, 1/04/2023, 18:12, mfg92 ***@***.***> escreveu:

**Comment by mfg92** [comment]
I don't know anything about Openhantek, so I can't help you.

**Comment by UpDownSide** [comment]
Thanks! But what soft do you use?

A sábado, 1/04/2023, 20:09, mfg92 ***@***.***> escreveu:

**Comment by mfg92** [comment]
I do not use any other software. This is a standalone application. You have to use the [commandline ](https://en.wikipedia.org/wiki/Command-line_interface) (like cmd or bash)  to start the application. The application has no graphical userinterface.
